//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bluesoft.Web.Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlSitioTrabajo
    {
        public int IdControlSitioTrabajo { get; set; }
        public int IdTienda { get; set; }
        public int IdEmpleado { get; set; }
        public System.DateTime FechaIngreso { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Tienda Tienda { get; set; }
    }
}
